version: "3.9"

services:
  server:
    image: hack4good-app
    build: .
    ports:
      - "4000:4000"
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
